### PR TITLE
Update to 2.5 rules & new pages for devices

### PR DESCRIPTION
**Pull request by gabindu**
I've updated your great document for the latest rules, and added new pages for devices. (The only thing I had to remove for space reasons was the "setup".) Let me know what you think!

(I've also included the pdf-file in the repo, mainly for my own convenience - but you could of course ignore that, if you publish as a release.)

### CODE REVIEW

**Comment by brobzilla** [comment]
This is an amazing update!  Thank you for doing this.  


Gas Cloud says "Breaks all locks on or from your ship."  Would it be more clear to say "Breaks all locks on **and** from your ship"


If this change makes sense I think electro-chaff could use the same update.

**Comment by gabindu** [comment]
Nice catch, I just changed that for both.

**Comment by npiegdon** [comment]
I just pushed this as a new release.  Thanks again!  That bumping diagram is great.

I usually make a post at [r/XWingTMG](https://www.reddit.com/r/XWingTMG/) pointing to the new release, but since this was all your work, you deserve the credit there, too.  So, feel free to make the update post there (assuming you're a Reddit user and are interested, etc.).

**Comment by gabindu** [comment]
I'm glad you like it! But thanks to you for creating the 2.0 version in the first place - I mainly just shuffled things around. ;-)   I'll indeed make a post at r/XWingTMG in a bit, thanks for the offer.  By the way, I just finished making a custom version which also includes a third sheet specific to the Heroes of the Aturi Cluster campaign (which is what got me started on this in the first place!). I'll keep that separate in my own repository, since it's not for generic X-Wing play: https://github.com/gabindu/xwing2-quick-reference/tree/hotac  (I've now also updated the README there to properly point back to your repository and explain the content changes.)

**Comment by npiegdon** [comment]
That HotAC sheet looks awesome too.  One of the reasons I haven't played in a while is because I prefer PvE/co-op to PvP games.  I've been meaning to try HotAC for a while and maybe I will now that there is a handy quick reference card available! 😄

**Pull request merged**
